### ISSUE TITLE
Got 500 error when trying to Save a custom app nam

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#711] opened 2016-09-08 21:45 UTC
Server: cloud.pilrhealth.com
Page: /project/buckeye_teen_healthtest/emaOts/application
User: pbrown
Project: buckeye_teen_healthtest

works on qa but not cloud

**Comment by tdschenk** [comment] 2016-09-15 21:20
duplicate of 712. fix is on qa but not cloud yet

**Closed by tdschenk** 2016-09-15 21:20 UTC
