### ISSUE TITLE
Permissions summary in administration

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#639] opened 2016-08-04 17:57 UTC
Server: qa.pilrhealth.com
Page: /project/erictest2/project/admin
User: eruud
Project: erictest2

Why does lock show up twice in my list of permissions?

**Comment by eruud** [comment] 2016-08-04 17:58
![image](https://cloud.githubusercontent.com/assets/19293109/17412596/2fa7478e-5a43-11e6-917a-cbc783b971c7.png)

**Comment by eruud** [comment] 2016-11-14 20:21
No longer see duplicate of lock permission in my projects

**Closed by eruud** 2016-11-14 20:21 UTC
