### ISSUE TITLE
Unable to Export New EMA Config

### ISSUE THREAD

**Issue by bikerjohn** [pilrhealth/pilrhealth-issues#439] opened 2016-01-12 22:03 UTC
Test Scenario
Created new project
Imported Instrument
Created EMA Config
Created New Survey
Created New Trigger
Tried to Export EMA Config -- received 500 error message

**Comment by mgm7734** [comment] 2016-01-14 15:40
@bikerjohn can you close this issue if it's resolved to your satisfaction?

**Comment by bikerjohn** [comment] 2016-01-14 17:32
I would close it, but as of 10:00am this morning I am still unable to
export an EMA config from a new project using the new trigger editor.

On Thu, Jan 14, 2016 at 9:40 AM, Mark Mendel <notifications@github.com>
wrote:

> @bikerjohn <https://github.com/bikerjohn> can you close this issue if
> it's resolved to your satisfaction?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pilrhealth/pilrhealth-issues/issues/439#issuecomment-171676808>
> .
>



-- 
John J. Shade

**Comment by bikerjohn** [comment] 2016-01-19 17:56
Test Procedure
Used a project enabled for v2-api
created ema config
created survey
created new style trigger
exported ema config
created a new project
enabled the project for v2api
tried to import the ema config
received the following failure
![v2api_import_failure](https://cloud.githubusercontent.com/assets/11665857/12427232/b6ea6dde-bea3-11e5-8b69-e733b6ef27ae.PNG)

**Comment by jmusacchio-gap** [comment] 2016-01-19 18:31
Seems that the export works fine so you can close it. Now the problem is in the import, it s crashing on EmaOtsTriggerCriteriaTrigger (old trigger library) when assigning maxFiringPerDay with a JSONObject.Null. Feel free to fire a new bug, I'm already working on it.

**Closed** 2016-01-19 19:58 UTC
Labels: bug, ready 4 test
