### ISSUE TITLE
Plotting Options - Quick plot setup

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#540] opened 2016-05-10 18:56 UTC
Server: qa.pilrhealth.com
Page: /project/calorimetertest516/quickPlotItem/create/57322e54e4b0326397865520
User: ewohlers
Project: calorimetertest516

I was able to create 1 quick plot. When I tried to create a second quick plot, there was not drop down for the Data Field option.

**Comment by tdschenk** [comment] 2016-05-10 20:45
Duplicate of https://github.com/pilrhealth/pilrhealth-issues/issues/407

Only occurs when you try to create two quick plot items in a row without accessing a different screen in between. When accessing the /quickPlotItem/create screen the second time, the id from the first quick plot item is appended to the URL as seen above and must be causing the issue.

**Comment by tdschenk** [comment] 2016-05-17 18:35
Imad fixed this but it has not been committed yet

**Comment by tdschenk** [comment] 2016-05-17 19:11
Fix pushed by Imad

**Closed by tdschenk** 2016-05-17 19:11 UTC
