### ISSUE TITLE
App Sleep time end

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#452] opened 2016-01-18 20:47 UTC
Server: cloud.pilrhealth.com
Page: /project/b-mobile_test/participant/show/569cf2b2e4b068db98766eb4
User: jgthomas
Project: b-mobile_test

When I try to change the value for App Sleep time end I get the message "Please correct the errors shown below" and the box for the time entry is highlighted. However, I cannot seem to find anything wrong with the entry. I even get this message if I do not change the entry and just leave what is already there.

**Comment by bikerjohn** [comment] 2016-01-18 22:11
Jon and I (Shade) looked at this issue on cloud.  It appears to be a general problem with how we are handling the time picker when we save.  I would guess it affects ALL instrument settings on cloud.

**Comment by paul-ferguson** [comment] 2016-01-19 21:38
This should be fixed on the next build I think. The issue is that the time picker shouldn't show the seconds field and I believe it was Juan that fixed this. Regardless it should already be fixed.

**Comment by jmusacchio-gap** [comment] 2016-01-20 11:47
This issue seems to match this assembla ticket https://www.assembla.com/spaces/cACHIMvRir44okacwqjQYw/tickets/new_cardwall?default_list_cardwall=filter:5#ticket:1458 that already fixed. Not sure whether cloud has the latest version, but for sure QA should have it fix it.

**Closed** 2016-06-21 15:31 UTC
Labels: bug, ready 4 test
